stage('Build') {
    steps {
        dir('Hello') {
            bat 'mvn clean package'
        }
    }
}
stage('Test') {
    steps {
        dir('Hello') {
            bat 'mvn test'
        }
    }
    post {
        always {
            junit 'Hello/target/surefire-reports/*.xml'
        }
    }
}
stage('Deploy') {
    steps {
        dir('Hello') {
            bat 'java -jar target/ci-cd-demo-1.0-SNAPSHOT.jar'
        }
    }
}
